'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblAsesor
    Public Property DNI As String
    Public Property Nombres As String
    Public Property Apellidos As String

    Public Overridable Property tblEmpresa As ICollection(Of tblEmpresa) = New HashSet(Of tblEmpresa)

End Class
