'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblEmpresa
    Public Property Codigo As Integer
    Public Property RUC As String
    Public Property RazonSocial As String
    Public Property Tipo As String
    Public Property CodigoRubro As String
    Public Property DNIAsesor As String

    Public Overridable Property tblAsesor As tblAsesor
    Public Overridable Property tblRubro As tblRubro

End Class
